version: "3.8"

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FTBA"
      FTB_MODPACK_ID: "FTBRevelation"
      FTB_MODPACK_VERSION_ID: "3.7.0"
    volumes:
      - ./data:/data
    restart: unless-stopped
