FROM itzg/minecraft-server:java8

ENV TYPE=FTBA \
    FTB_MODPACK_ID=35 \
    FTB_MODPACK_VERSION_ID=12180 \
    EULA=TRUE \
    JAVA_VERSION=8 \
    MEMORY=4G \
    JVM_OPTS="-XX:+UseG1GC -XX:MaxGCPauseMillis=50"

EXPOSE 25565

VOLUME /data
